name: WardBuilder
version: 0.0.1
load: STARTUP
author: MrLizzard
description: Build plugin delivred for Wardevil.
main: fr.mrlizzard.wardevil.builder.WardBuilder
database: false

commands:
  build:
    description: Command for WardBuilder plugin.
    usage: "Usage: /build help"
    aliases: [b, wardbuild]
    permission: wardbuild.execute